"""Feature engineering for the real-time sales forecasting pipeline.

This module takes raw sales data, generates time-based features, lag features,
rolling averages, and holiday flags, and prepares a final feature matrix for modeling.
"""

import argparse
import logging
from typing import List

import pandas as pd

LOGGER = logging.getLogger("sales_forecasting.features")


def configure_logging(level: str = "INFO") -> None:
    """Configure structured logging for feature engineering runs."""
    logging.basicConfig(
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    )


def load_raw_data(source: str) -> pd.DataFrame:
    """Load normalized raw data.
    
    For production, this would load from PostgreSQL. For testing, it loads from a local CSV.
    """
    LOGGER.info("Loading raw data from %s", source)
    df = pd.read_csv(source)
    df["Date"] = pd.to_datetime(df["Date"])
    return df


def generate_time_features(df: pd.DataFrame) -> pd.DataFrame:
    """Generate calendar and time-based features."""
    LOGGER.info("Generating time-based features...")
    df = df.copy()
    
    df["day_of_week"] = df["Date"].dt.dayofweek
    df["day_of_month"] = df["Date"].dt.day
    df["month"] = df["Date"].dt.month
    df["year"] = df["Date"].dt.year
    df["is_weekend"] = df["day_of_week"].isin([5, 6]).astype(int)
    
    return df


def generate_lag_features(df: pd.DataFrame, lags: List[int] = [7, 14, 30]) -> pd.DataFrame:
    """Generate lag features for Sales.
    
    Assumes data is sorted by Date within each Store.
    """
    LOGGER.info("Generating lag features for %s days...", lags)
    df = df.copy()
    
    df = df.sort_values(by=["Store", "Date"])
    for lag in lags:
        df[f"Sales_lag_{lag}"] = df.groupby("Store")["Sales"].shift(lag)
        
    return df


def generate_rolling_features(df: pd.DataFrame, windows: List[int] = [7, 14, 30]) -> pd.DataFrame:
    """Generate rolling averages for Sales.
    
    Assumes data is sorted by Date within each Store.
    """
    LOGGER.info("Generating rolling window features for %s days...", windows)
    df = df.copy()
    
    df = df.sort_values(by=["Store", "Date"])
    for window in windows:
        # shift(1) ensures we don't leak current day's sales into the rolling mean
        df[f"Sales_roll_mean_{window}"] = (
            df.groupby("Store")["Sales"]
            .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
        )
        
    return df


def encode_categorical_features(df: pd.DataFrame) -> pd.DataFrame:
    """Encode categorical variables like StateHoliday."""
    LOGGER.info("Encoding categorical features...")
    df = df.copy()
    
    # StateHoliday in Rossmann dataset has '0', 'a', 'b', 'c'
    # We'll map anything that is not '0' or 0 to a generic "is_holiday" flag
    if "StateHoliday" in df.columns:
        df["StateHoliday"] = df["StateHoliday"].astype(str).str.strip()
        df["is_state_holiday"] = (df["StateHoliday"] != "0").astype(int)
        
    # SchoolHoliday is already an indicator (0 or 1)
    if "SchoolHoliday" in df.columns:
        df["SchoolHoliday"] = df["SchoolHoliday"].astype(int)
        
    return df


def process_features(df: pd.DataFrame) -> pd.DataFrame:
    """Run the complete feature engineering pipeline."""
    
    df = generate_time_features(df)
    df = generate_lag_features(df)
    df = generate_rolling_features(df)
    df = encode_categorical_features(df)
    
    # Drop rows with NA values generated by lag features if needed
    # For now, we will leave them, as XGBoost can handle missing values,
    # or we can fill them. Let's forward fill then fill with 0.
    df = df.fillna(0)
    
    LOGGER.info("Feature engineering complete. Output shape: %s", df.shape)
    return df


def main():
    parser = argparse.ArgumentParser(description="Generate features for sales forecasting.")
    parser.add_argument("--source", required=True, help="Input CSV file path with raw normalized data.")
    parser.add_argument("--output", required=True, help="Output CSV file path for engineered features.")
    parser.add_argument("--log-level", default="INFO", help="Logging level.")
    
    args = parser.parse_args()
    configure_logging(args.log_level)
    
    raw_data = load_raw_data(args.source)
    engineered_data = process_features(raw_data)
    
    LOGGER.info("Saving engineered features to %s", args.output)
    engineered_data.to_csv(args.output, index=False)
    LOGGER.info("Done.")


if __name__ == "__main__":
    main()
